#!/usr/bin/env node
// Assembles dist-web/ — the installable web build, which is how this runs on
// Android.
//
// There is no bundler, because there is nothing to bundle: src/ is already
// plain ES modules and the app has no runtime dependencies. This copies the
// same files the desktop app loads, adds a manifest, icons and a service
// worker, and points index.html at them.
//
//   node tools/build-web.mjs [--out dist-web]

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { TAG_SIDECARS } from './apply-animations.mjs';

import { iconBuffer } from './make-icon.mjs';

const ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const args = process.argv.slice(2);
const outDir = path.resolve(
  args.includes('--out') ? args[args.indexOf('--out') + 1] : path.join(ROOT, 'dist-web'),
);

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

/* ------------------------------------------------------------------ app files */

const copied = [];

function copyDir(from, to, filter = () => true) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) {
      if (entry.name.startsWith('_')) continue; // puzzles/_raw and friends
      copyDir(src, dst, filter);
    } else if (filter(entry.name)) {
      fs.copyFileSync(src, dst);
      copied.push(path.relative(outDir, dst).split(path.sep).join('/'));
    }
  }
}

copyDir(path.join(ROOT, 'src'), outDir);
// The tag sidecars are build-time only: mapify bakes their contents into the
// puzzle files, so the client never fetches them and they do not ship.
copyDir(path.join(ROOT, 'puzzles'), path.join(outDir, 'puzzles'),
  (n) => n.endsWith('.json') && !TAG_SIDECARS.has(n));

/* ---------------------------------------------------------------------- icons */

// 192 and 512 are what the manifest spec expects; the maskable copy is padded
// so Android can crop it to a circle or squircle without eating the artwork.
const icons = [
  { file: 'icon-192.png', size: 192, purpose: 'any' },
  { file: 'icon-512.png', size: 512, purpose: 'any' },
  { file: 'icon-maskable-512.png', size: 512, purpose: 'maskable', square: true, padding: 0.14 },
  { file: 'apple-touch-icon.png', size: 180, purpose: 'any' },
];

for (const icon of icons) {
  fs.writeFileSync(
    path.join(outDir, icon.file),
    iconBuffer(icon.size, { square: icon.square, padding: icon.padding }),
  );
  copied.push(icon.file);
}

/* -------------------------------------------------------------------- manifest */

const manifest = {
  name: 'paintblob',
  short_name: 'paintblob',
  description: 'Paint by number, with big satisfying paint blobs.',
  start_url: '.',
  scope: '.',
  display: 'standalone',
  orientation: 'any',
  background_color: '#17151f',
  theme_color: '#17151f',
  categories: ['games', 'entertainment'],
  icons: [
    { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: 'icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};

fs.writeFileSync(
  path.join(outDir, 'manifest.webmanifest'),
  `${JSON.stringify(manifest, null, 2)}\n`,
);
copied.push('manifest.webmanifest');

/* ------------------------------------------------------------------ index.html */

// The desktop build must not carry these tags — Electron has no manifest and
// no service worker, and a 404 for either shows up as a console error.
const indexPath = path.join(outDir, 'index.html');
const html = fs.readFileSync(indexPath, 'utf8').replace(
  '<link rel="icon" href="data:," />',
  [
    '<link rel="icon" href="icon-192.png" />',
    '  <link rel="apple-touch-icon" href="apple-touch-icon.png" />',
    '  <link rel="manifest" href="manifest.webmanifest" />',
  ].join('\n  '),
);
if (html === fs.readFileSync(indexPath, 'utf8')) {
  throw new Error('index.html icon placeholder not found — the injection anchor moved');
}
fs.writeFileSync(indexPath, html);

/* -------------------------------------------------------------- service worker */

// Version the cache by content. Any change to any shipped file produces a new
// cache name, so an update never serves half the old app and half the new one.
const digest = crypto.createHash('sha256');
for (const rel of [...copied].sort()) {
  digest.update(rel);
  digest.update(fs.readFileSync(path.join(outDir, rel)));
}
const version = digest.digest('hex').slice(0, 12);

const precache = [...new Set(['.', ...copied])].sort();

fs.writeFileSync(path.join(outDir, 'sw.js'), `// Generated by tools/build-web.mjs — do not edit.
const CACHE = 'paintblob-${version}';
const ASSETS = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Cache-first. Everything here is static and the cache name changes whenever
// any file does, so there is nothing to revalidate.
self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  if (new URL(event.request.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(event.request, { ignoreSearch: true })
      .then((hit) => hit || fetch(event.request)),
  );
});
`);

/* --------------------------------------------------------------------- report */

const bytes = precache
  .filter((f) => f !== '.')
  .reduce((sum, f) => sum + fs.statSync(path.join(outDir, f)).size, 0);

console.log(`${path.relative(ROOT, outDir)}/`);
console.log(`  ${precache.length - 1} files, ${(bytes / 1024).toFixed(0)} kB total`);
console.log(`  cache version ${version}`);
console.log(`\nserve it over https (or localhost) — service workers refuse file://`);
console.log(`  npx serve ${path.relative(ROOT, outDir)}`);
